#!gmake

CPPMD=python ../cppmd_render.py

all: $(addsuffix .pdf,$(basename $(wildcard *.cppmd)))

%.pdf: %.cppmd
	cat ../header.yml > .$<
	head -n 1 $< >> .$<
	cat ../header.cppmd >> .$<
	cat $< >> .$<
	$(CPPMD) --prefix .$(@:%.pdf=%) --beamer-theme=metropolis --force --dont-update-gitignore < .$<
	mv .$@ $@

.PHONY: clean
clean:
	rm -f *.pdf *.md *.c *.cpp *.h *.hpp *.o a.out *~
