#!gmake

CPPMD=python ../cppmd_render.py

all: $(addsuffix .pdf,$(basename $(wildcard *.cppmd)))

%.pdf: %.cppmd
	cat ../header.yml > .$(@:%.pdf=%)
	head -n 1 $< >> .$(@:%.pdf=%)
	cat ../header.cppmd >> .$(@:%.pdf=%)
	cat $< >> .$(@:%.pdf=%)
	$(CPPMD) --prefix .$(@:%.pdf=%) --beamer-theme=metropolis --force --dont-update-gitignore < $<

.PHONY: clean
clean:
	rm -f *.pdf *.md *.c *.cpp *.h *.hpp a.out *~
